# Generated by Django 3.1.1 on 2020-09-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64, verbose_name='Откуда')),
                ('departure', models.DateField(verbose_name='Departure')),
                ('destination', models.CharField(max_length=64, verbose_name='Куда')),
                ('price', models.IntegerField(verbose_name='Cтоимость')),
                ('company', models.CharField(max_length=64, verbose_name='Компания')),
                ('isBusiness', models.BooleanField(default=False, verbose_name='Класс')),
                ('isPlane', models.BooleanField(default=True, verbose_name='Самолет')),
                ('isTrain', models.BooleanField(default=False, verbose_name='Поезд')),
                ('isBus', models.BooleanField(default=False, verbose_name='Автобус')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('distance', models.IntegerField(verbose_name='Дистанция')),
            ],
        ),
    ]
